# /backend/configs/ingestion/insurance/auto_policy_chunks.yaml

# Unique identifier for this report type.
report_type: "AUTO_POLICY_CHUNKS"

# Reusing KNOWLEDGE_CHUNK to build a unified, searchable corpus of documents.
item_type: "KNOWLEDGE_CHUNK"

# We'll use the 'document name' to scope these chunks to the auto policy.

# Business key is a composite of the unique document ID and the chunk number.
business_key:
  - "metadata.document_id"
  - "metadata.chunk_number"

scope_field: "document name"

# Tell the engine to create vector embeddings from the 'chunked text' column for the RAG AI.
embed_content:
  source_columns:
    - "chunk_text"

column_mappings:
  - csv_header: "document name"
    json_field: "scope"
    validation:
      required: true

  - csv_header: "document id"
    json_field: "metadata.document_id"
    validation:
      required: true

  - csv_header: "chunk number"
    json_field: "metadata.chunk_number"
    attempts:
      - transforms:
          - "to_integer"
    validation:
      required: true

  - csv_header: "last updated"
    json_field: "metadata.last_update"
    attempts:
      - transforms:
          # Assuming the same "Month Day, Year" format like "January 1, 2025"
          - "to_date:2-Jan-06"
    validation:
      required: false

  - csv_header: "section"
    json_field: "metadata.section"
    validation:
      required: false

  # This handles the JSON string in the 'custom properties' column from the CSV
  - csv_header: "custom properties"
    json_field: "metadata.source_custom_properties"
    validation:
      required: false

  - csv_header: "chunked text"
    json_field: "chunk_text"
    validation:
      required: true
