# /backend/configs/ingestion/insurance/internal_claims_guide.yaml

report_type: "CLAIM_HANDLING_PROTOCOL"
item_type: "KNOWLEDGE_CHUNK"
business_key:
  - "metadata.document_id"
  - "metadata.chunk_number"
embed_content:
  source_columns:
    - "chunk_text"

column_mappings:
  - csv_header: "document name"
    json_field: "scope"
    validation:
      required: true

  - csv_header: "chunked text"
    json_field: "chunk_text"
    validation:
      required: true

  - csv_header: "document id"
    json_field: "metadata.document_id"
    validation:
      required: true

  - csv_header: "chunk number"
    json_field: "metadata.chunk_number"
    attempts:
      - transforms:
          - "to_integer"
    validation:
      required: true

  - csv_header: "section"
    json_field: "metadata.section"
    validation:
      required: false

  - csv_header: "last updated"
    json_field: "metadata.last_update"
    attempts:
      - transforms:
          - "to_date:2-Jan-06"
      - transforms:
          - "to_date:2006-01-02"
    validation:
      required: false
  
  - csv_header: "custom properties"
    json_field: "metadata.source_custom_properties"
    validation:
      required: false
